### ISSUE TITLE
Implementer should be able to provide the subject on which the visit is to be scheduled

### ISSUE THREAD

**Issue by arjunk** [OpenCHS/rules-config#7]
### Acceptance Criteria
1. As an implementer I should be able to specify if i want to schedule an encounter for another subject by specifying subject uuid and program uuid.
2. As an implementer, if I don't specify a subject uuid, it should default to the current behaviour that is assuming it is the same subject as that on which the current encounter is being performed.
3. Other behaviour like not allowing duplicate visits, etc should remain the same. 

### Tech
1. Add two params (subject uuid, program uuid)in the visit schedule builder https://github.com/avniproject/rules-config/blob/master/src/rules/builder/VisitScheduleBuilder.js#L38. subjectUUID
2. Update the tests also. https://github.com/avniproject/rules-config/blob/master/test/VisitScheduleBuilderTest.js

**Comment by 1t5j0y** [comment]
Not required as the visit schedule object automatically includes any additional parameters specified by the implementer.
